[build]
  # Base directory for the build command
  base = "."

  # Directory to change to before starting build
  command = "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port $PORT"

  # Functions directory
  functions = "lambda"

  # Directory to publish (relative to root of your repo)
  publish = "."

# Settings for the deploy
[settings]
  # A string to prefix to your site's URL
  # If not provided, one will be generated
  # Used for functions and deploy previews
  site = "snapgredient"